name: Build WatchFix Native Roothide

on:
  workflow_dispatch: # 保留了这个，意味着你可以随时手动点击运行

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Checkout roothide/theos
        id: checkout_theos
        uses: actions/checkout@main
        with:
          repository: roothide/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        id: checkout_sdks
        if: steps.checkout_theos.outcome == 'success'
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          sparse-checkout: iPhoneOS16.5.sdk
          path: theos/sdks
        
      - name: Install Dependencies
        id: install_deps
        if: steps.checkout_sdks.outcome == 'success'
        run: |
          brew install make ldid

      - name: Build Rootless Package
        id: build_rootless
        if: steps.install_deps.outcome == 'success'
        env:
          THEOS: theos
        run: |
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload a Rootless Build Artifact
        if: steps.build_rootless.outcome == 'success'
        uses: actions/upload-artifact@v4  # 【关键修正】：v7 改为官方最新的 v4
        with:
          name: rootless-package
          path: packages/rootless/*.deb
          retention-days: 15
          archive: false
  
      - name: Build Roothide Package
        id: build_roothide
        if: steps.install_deps.outcome == 'success'
        env:
          THEOS: theos
        run: |
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide
        
      - name: Upload a Roothide Build Artifact
        if: steps.build_roothide.outcome == 'success'
        uses: actions/upload-artifact@v4  # 【关键修正】：v7 改为官方最新的 v4
        with:
          name: roothide-package
          path: packages/roothide/*.deb
          retention-days: 15
          archive: false
